### ISSUE TITLE
Ondc:ret10 inc refresh not able to test 

### ISSUE THREAD

**Issue by venkatramanm** [ONDC-Official/log-validation-utility#3]
Gives contradictory errors that cannot be fixed. If the input is fixed for a reported error, the fix becomes the issue. 

{
  "success": false,
  "response": {
    "search_inc_refresh": {
      "intent": {
        "tags": null
      }
    },
    "on_search_inc_refresh": {
      "schemaErr0": "/message/catalog/bpp~1providers/0/items/0/category_id must be equal to one of the allowed values (Baklava,Bao,Barbecue,Biryani,Bread,Burger,Cakes,Chaat,Cheesecakes,Chicken,Chicken wings,Chips,Coffee,Cookies,Crepes,Dal,Desserts,Dhokla,Dosa,Doughnuts,Eggs,Energy Drinks,Falafel,Fresh Juice,Fries,Ice cream,Idli,Kabab,Kachori,Kulfi,Lassi,Meal bowl,Mezze,Mithai,Momos,Mutton,Nachos,Noodles,Pakodas,Pancakes,Paneer,Pasta,Pastries,Pie,Pizza,Poha,Raita,Rice,Rolls,Roti,Salad,Samosa,Sandwich,Seafood,Shakes & Smoothies,Soft Drink,Soup,Spring Roll,Sushi,Tacos,Tandoori,Tart,Tea,Thali,Tikka,Upma,Uttapam,Vada,Vegetables,Waffle,Wrap,Yogurt,F&B)",
      "locationTimeLabel": "location label (/bpp/providers/locations/time/label) for /on_search_inc_refresh should not be equal to /on_search_full_catalog_refresh.label",
      "prvdr0item0ff": "fulfillment_id in /bpp/providers[0]/items[0] should map to one of the fulfillments id in bpp/fulfillments"
    }
  }
}
--
I am getting this errors. I am unable to fix.
 search_inc_refresh has tags.
 on_search_inc, The category_id of my item is Pet Care. All the category_ids reported seems to be of f&B?
 "bpp/fulfillments" if passed, it says dont pass  but expects fulfillment_id to be part of bpp/fulfillments. May be it should be checking against provider /fulfillments. not sure. 
 Only my item is disabled but the location has no change. If I pass location it expects time attribute should not be same with full search. If I dont pass time, it asks for time, If i dont pass location, It want it to be passed. Not sure what is needed.

**Comment by venkatramanm** [comment]
https://ondc.enterprise.slack.com/files/U03GGLA8XUN/F064LFSUD6Z/ondcvalidator_payload.json

**Comment by venkatramanm** [comment]
https://ondc.enterprise.slack.com/files/U03GGLA8XUN/F064LFSUD6Z/ondcvalidator_payload.json
@bluecypher @sahilsharma9

**Comment by venkatramanm** [comment]
Todays Log Validation Report:

``{
  "success": false,
  "response": {
    "search_inc_refresh": {
      "intent": {
        "tags": null
      }
    },
    "on_search_inc_refresh": {
      "bppFulfillments": "bpp/fulfillments sent in payload shoulnd't be part of /on_search_inc_refresh api",
      "locationTimeLabel": "location label (/bpp/providers/locations/time/label) for /on_search_inc_refresh should not be equal to /on_search_full_catalog_refresh.label",
      "prvdr0item0ff": "fulfillment_id in /bpp/providers[0]/items[0] should map to one of the fulfillments id in bpp/fulfillments"
    }
  }
}``
bppFulfillments and prvdr0item0ff cannot be satisfied together. ! 
locationTimeLabel can be same as I need to pass location_id on the item and it has to be there in the locations. My Item is deactivated but not location. 

Thanks for fixing Pet Care category being made valid @bluecypher  @sahilsharma9

**Comment by sharmasahil0331** [comment]
Issues has been resolved, Please check

@venkatramanm

**Comment by venkatramanm** [comment]
Still seeing some errors. 

"error": {
    "success": false,
    "response": {
      "search_inc_refresh": {
        "intent": {
          "tags": null
        }   
      },      
      "on_search_inc_refresh": {
        "locationTimeLabel": "location label (/bpp/providers/locations/time/label) for /on_search_inc_refresh should not be equal to /on_search_full_catalog_refresh.label"
      }
    }

1.  tags was passed! 
2.  "locationTimeLabel":  item label has changed. What am i expected to send for location? 
      * If I don't pass locations array, it demands that I pass it.
      * If I pass it demands that label attribute should be present.
      * I have not changed the location label. So pretty much I am stuck.

**Comment by venkatramanm** [comment]
[ondcvalidator_payload.json](https://github.com/ONDC-Official/log-validation-utility/files/13442631/ondcvalidator_payload.json)

Check this payload file and see what can be done. @sahilsharma9

**Comment by sandeepshahi** [comment]
Fixed
